apiVersion: apps/v1
kind: Deployment
metadata:
  name: amb-ambulance-webapi
spec:
  template:
   spec:
      initContainers:
        - name: init-mongodb
          env:
            - name: AMBULANCE_API_MONGODB_HOST
              value: null
              valueFrom:
                configMapKeyRef:
                  name: mongodb-connection
                  key: host
            - name: AMBULANCE_API_MONGODB_PORT
              value: null
              valueFrom:
                configMapKeyRef:
                  name: mongodb-connection
                  key: port
      containers:
        - name: amb-ambulance-wl-webapi-container
          env:
            - name: AMBULANCE_API_MONGODB_HOST
              value: null
              valueFrom:
                configMapKeyRef:
                  name: mongodb-connection
                  key: host
            - name: AMBULANCE_API_MONGODB_PORT
              value: null
              valueFrom:
                configMapKeyRef:
                  name: mongodb-connection
                  key: port